### ISSUE TITLE
3.6.10

### ISSUE THREAD

**Issue by YtvwlD** [iusrepo/python36u#12]
Python 3.6.10 has been [released](https://www.python.org/downloads/release/python-3610/) in December and it would be great if this repository could be updated.

I tried to update it myself and it seems to work, but I have never packaged an RPM before or something like this. The latest commit in [this gist](https://gist.github.com/YtvwlD/333d38e2c17b101d2bc991f11c6b2525) makes 3.6.10 build fine at least and the interpreter seems to be usable.

**Comment by carlwgeorge** [comment]
Thank you for your effort on this, but because [Python 3.6 is now available from the base distribution (python3)](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.7_release_notes/new_features#enhancement_compiler-and-tools), this package is deprecated.  No further releases are planned.  I'll archive this repo to make the status more clear.

If there are IUS packages you depended on previously that are not available in base or EPEL, please discuss them [here](https://github.com/iusrepo/packaging/issues/7) and myself or someone else may be able to help.
