### ISSUE TITLE
update python36u to 3.6.9 ( for RHEL 6 )? 

### ISSUE THREAD

**Issue by matthewroberson71** [iusrepo/python36u#9]
My company has a regulatory requirement to do monthly security patch reviews and since our last review version 3.6.9 was released and it includes some security patches (CVE-2019-9948, CVE-2019-9740, CVE-2019-5010).  We have two RHEL 6 servers with this installed. Thanks.

**Comment by carlwgeorge** [comment]
Thanks for reporting this @matthewroberson71.  [CVE-2019-5010 is already patched in the package](https://github.com/iusrepo/python36u/commit/55d0ce619f900d4d9d94878433935b72db0e3184).  The other two aren't.  I'm not going to update it to 3.6.9 at this time because that would interfere with my [python3 consolidation plan](https://github.com/iusrepo/packaging/issues/7), but the new RHEL 7 python3 package includes backport patches to fix those CVEs.  I can add them to the python36 package for EL6.

- [CVE-2019-9740](https://git.centos.org/rpms/python3/blob/c7/f/SOURCES/00324-disallow-control-chars-in-http-urls.patch)
- [CVE-2019-9948](https://git.centos.org/rpms/python3/blob/c7/f/SOURCES/00325-CVE-2019-9948.patch)

**Comment by carlwgeorge** [comment]
python36-3.6.8-2 has just been published to the testing repo for both EL6 and EL7.  It includes fixes for all the CVEs you mentioned.  I need to keep it in the testing repos until I finish python34 as well, so I can release them to stable at the same time.
